<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DateJobSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('date_jobs')->insert([
            [
                'user_id' => 1,
                'girl_id' => 1,
                'date_of_date' => '2023/07/23',
                'time_of_date' => '18:00',
                'place_of_date' => '六本木',
                'passion'=>'初対面。仲良くなる。',
                'target'=>'次のデートに備える。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'girl_id' => 1,
                'date_of_date' => '2024/01/20',
                'time_of_date' => '18:00',
                'place_of_date' => '広尾',
                'passion'=>'なんでも話せる仲になる。',
                'target'=>'相手の理解者となる。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'girl_id' => 2,
                'date_of_date' => '2024/01/25',
                'time_of_date' => '20:00',
                'place_of_date' => '渋谷',
                'passion'=>'相互理解をする。',
                'target'=>'まずは楽しむ。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'girl_id' => 3,
                'date_of_date' => '2023/12/20',
                'time_of_date' => '18:00',
                'place_of_date' => '北千住',
                'passion'=>'ありのままを演出する。。',
                'target'=>'楽しませる。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'girl_id' => 4,
                'date_of_date' => '2023/12/15',
                'time_of_date' => '20:00',
                'place_of_date' => '丸の内',
                'passion'=>'おしゃれにきめたい。',
                'target'=>'引き出しを増やす。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'girl_id' => 5,
                'date_of_date' => '2024/01/25',
                'time_of_date' => '18:00',
                'place_of_date' => '秋葉原',
                'passion'=>'趣味を追求する。',
                'target'=>'メイドカフェに行く。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'girl_id' => 6,
                'date_of_date' => '2023/12/20',
                'time_of_date' => '18:00',
                'place_of_date' => '品川',
                'passion'=>'アクアリウムでいい雰囲気に。',
                'target'=>'相手の深いところまで話を聞く。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'girl_id' => 7,
                'date_of_date' => '2023/12/20',
                'time_of_date' => '18:00',
                'place_of_date' => '浜松町',
                'passion'=>'チルスポットに行きたい。',
                'target'=>'一緒に乾杯する。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'girl_id' => 8,
                'date_of_date' => '2023/12/20',
                'time_of_date' => '18:00',
                'place_of_date' => '新宿',
                'passion'=>'歌舞伎で飲む。',
                'target'=>'肩を組む。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 6,
                'girl_id' => 9,
                'date_of_date' => '2023/12/20',
                'time_of_date' => '18:00',
                'place_of_date' => '新宿',
                'passion'=>'楽しく買い物する。',
                'target'=>'相手の趣味を理解する。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 7,
                'girl_id' => 10,
                'date_of_date' => '2023/12/15',
                'time_of_date' => '20:00',
                'place_of_date' => '池袋',
                'passion'=>'アイドルのライブを見たい。',
                'target'=>'より相手のことを知る。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 8,
                'girl_id' => 11,
                'date_of_date' => '2024/01/25',
                'time_of_date' => '18:00',
                'place_of_date' => '西麻布',
                'passion'=>'会員制のバーに行く。',
                'target'=>'楽しませる。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'girl_id' => 12,
                'date_of_date' => '2024/02/24',
                'time_of_date' => '20:00',
                'place_of_date' => '恵比寿',
                'passion'=>'おしゃれに楽しむ。',
                'target'=>'カフェでゆっくり。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'girl_id' => 13,
                'date_of_date' => '2024/02/11',
                'time_of_date' => '18:00',
                'place_of_date' => '上野',
                'passion'=>'飲んだくれたい。',
                'target'=>'朝まで楽しむ。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'girl_id' => 14,
                'date_of_date' => '2023/11/25',
                'time_of_date' => '20:00',
                'place_of_date' => '代々木公園',
                'passion'=>'散歩しながら話を深めたい。',
                'target'=>'横に座る。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'girl_id' => 15,
                'date_of_date' => '2023/11/25',
                'time_of_date' => '20:00',
                'place_of_date' => '代々木公園',
                'passion'=>'ランニングをやりきる。',
                'target'=>'ダイエット仲間！',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 6,
                'girl_id' => 16,
                'date_of_date' => '2023/11/25',
                'time_of_date' => '20:00',
                'place_of_date' => '代々木公園',
                'passion'=>'キッチンカー楽しみ。',
                'target'=>'手を繋ぐ。',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
