<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DateJobSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('date_jobs')->insert([
            [
                'user_id' => 1,
                'girl_id' => 1,
                'date_of_date' => '2023/07/23',
                'time_of_date' => '18:00',
                'place_of_date' => '六本木',
                'passion'=>'まじで抱きしめたい',
                'target'=>'付き合う',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'girl_id' => 1,
                'date_of_date' => '2024/01/20',
                'time_of_date' => '18:00',
                'place_of_date' => '六本木',
                'passion'=>'まじで抱きしめたい',
                'target'=>'付き合う',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'girl_id' => 2,
                'date_of_date' => '2024/01/25',
                'time_of_date' => '20:00',
                'place_of_date' => '渋谷',
                'passion'=>'まじで抱きしめたい',
                'target'=>'付き合う',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'girl_id' => 3,
                'date_of_date' => '2023/12/20',
                'time_of_date' => '18:00',
                'place_of_date' => '北千住',
                'passion'=>'まじで抱きしめたい',
                'target'=>'付き合う',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'girl_id' => 4,
                'date_of_date' => '2023/12/15',
                'time_of_date' => '20:00',
                'place_of_date' => '丸の内',
                'passion'=>'まじで抱きしめたい',
                'target'=>'付き合う',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'girl_id' => 5,
                'date_of_date' => '2024/01/25',
                'time_of_date' => '18:00',
                'place_of_date' => '秋葉原',
                'passion'=>'まじで抱きしめたい',
                'target'=>'付き合う',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'girl_id' => 6,
                'date_of_date' => '2023/12/20',
                'time_of_date' => '18:00',
                'place_of_date' => '品川',
                'passion'=>'まじで抱きしめたい',
                'target'=>'付き合う',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 6,
                'girl_id' => 7,
                'date_of_date' => '2023/12/20',
                'time_of_date' => '18:00',
                'place_of_date' => '浜松町',
                'passion'=>'まじで抱きしめたい',
                'target'=>'付き合う',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 7,
                'girl_id' => 8,
                'date_of_date' => '2023/12/20',
                'time_of_date' => '18:00',
                'place_of_date' => '新宿',
                'passion'=>'まじで抱きしめたい',
                'target'=>'付き合う',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'girl_id' => 10,
                'date_of_date' => '2023/12/15',
                'time_of_date' => '20:00',
                'place_of_date' => '池袋',
                'passion'=>'まじで抱きしめたい',
                'target'=>'付き合う',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'girl_id' => 11,
                'date_of_date' => '2024/01/25',
                'time_of_date' => '18:00',
                'place_of_date' => '西麻布',
                'passion'=>'まじで抱きしめたい',
                'target'=>'付き合う',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'girl_id' => 12,
                'date_of_date' => '2024/02/24',
                'time_of_date' => '20:00',
                'place_of_date' => '恵比寿',
                'passion'=>'まじで抱きしめたい',
                'target'=>'付き合う',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'girl_id' => 13,
                'date_of_date' => '2024/02/11',
                'time_of_date' => '18:00',
                'place_of_date' => '上野',
                'passion'=>'まじで抱きしめたい',
                'target'=>'付き合う',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'girl_id' => 14,
                'date_of_date' => '2023/11/25',
                'time_of_date' => '20:00',
                'place_of_date' => '代々木公園',
                'passion'=>'まじで抱きしめたい',
                'target'=>'付き合う',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
