<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GirlsProfileSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('girls_profiles')->insert([
            [
            'name' => 'みかこ',
            'age' => 25,
            'occupation' => '化粧品会社',
            'image_url'=> 'hogehoge',
            'user_id' => 1,
            'feature_first'=>'綺麗め',
            'feature_second' =>'ノリ良し',
            'feature_third' =>'仕事人',
            'birthday'=>'2001-07-04',
            'address'=>'神奈川県川崎市',
            'hobby'=>'お菓子作り',
            'character'=>'明るい',
            'favorite_type_of_man'=>'前向きな人',
            'favorite_foods'=>'パン',
            'dislike_foods'=>'トマト',
            'opportunity_to_meet'=>'バーで知り合った',
            'notice'=>'上品な雰囲気で話も弾む。',
            'has_boyfriend'=>true,
            'count_of_dates'=>2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'れいな',
            'age' => 23,
            'occupation' => '不動産営業',
            'image_url'=> 'hogehoge',
            'user_id' => 1,
            'feature_first'=>'黒髪',
            'feature_second' =>'韓流',
            'feature_third' =>'聞き上手',
            'birthday'=>'',
            'address'=>'東京都北区',
            'hobby'=>'語学',
            'character'=>'丁寧',
            'favorite_type_of_man'=>'筋肉質',
            'favorite_foods'=>'フィナンシェ',
            'dislike_foods'=>'ナス',
            'opportunity_to_meet'=>'交流会で知り合った',
            'notice'=>'話し方が丁寧で落ち着く。',
            'has_boyfriend'=>true,
            'count_of_dates'=>2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'りょうか',
            'age' => 22,
            'occupation' => '公務員',
            'image_url'=> 'hogehoge',
            'user_id' => 1,
            'feature_first'=>'カメラ女子',
            'feature_second' =>'理系',
            'feature_third' =>'酒豪',
            'birthday'=>'',
            'address'=>'東京都葛飾区',
            'hobby'=>'登山',
            'character'=>'和を大切にする',
            'favorite_type_of_man'=>'価値観が似てる人',
            'favorite_foods'=>'カレー',
            'dislike_foods'=>'キュウリ',
            'opportunity_to_meet'=>'上野の居酒屋で知り合った',
            'notice'=>'真面目だけど面白い。',
            'has_boyfriend'=>true,
            'count_of_dates'=>2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'かほ',
            'age' => 23,
            'occupation' => '美容師',
            'image_url'=> 'hogehoge',
            'user_id' => 1,
            'feature_first'=>'ピンク髪',
            'feature_second' =>'ガーリー',
            'feature_third' =>'ジャニ系',
            'birthday'=>'',
            'address'=>'東京都新宿区',
            'hobby'=>'推し活',
            'character'=>'ユニーク',
            'favorite_type_of_man'=>'王子様みたいな人',
            'favorite_foods'=>'ケーキ',
            'dislike_foods'=>'ピーマン',
            'opportunity_to_meet'=>'美容院で知り合った',
            'notice'=>'世界観が面白い。',
            'has_boyfriend'=>true,
            'count_of_dates'=>2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'あすか',
            'age' => 22,
            'occupation' => '都市銀行',
            'image_url'=> 'hogehoge',
            'user_id' => 1,
            'feature_first'=>'丸顔',
            'feature_second' =>'国立文系卒',
            'feature_third' =>'旅行好き',
            'birthday'=>'',
            'address'=>'東京都港区',
            'hobby'=>'ホカンス',
            'character'=>'社交的',
            'favorite_type_of_man'=>'刺激的な人',
            'favorite_foods'=>'タイ料理',
            'dislike_foods'=>'チョコレート',
            'opportunity_to_meet'=>'就職活動時に知り合った',
            'notice'=>'海外志向で明るい。',
            'has_boyfriend'=>true,
            'count_of_dates'=>2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'さりな',
            'age' => 23,
            'occupation' => '看護師',
            'image_url'=> 'hogehoge',
            'user_id' => 1,
            'feature_first'=>'清楚系',
            'feature_second' =>'メガネ女子',
            'feature_third' =>'細身',
            'birthday'=>'',
            'address'=>'東京都目黒区',
            'hobby'=>'旅行',
            'character'=>'優しい',
            'favorite_type_of_man'=>'静かな人',
            'favorite_foods'=>'焼肉',
            'dislike_foods'=>'魚介類',
            'opportunity_to_meet'=>'友達の紹介',
            'notice'=>'白衣が似合いそう。',
            'has_boyfriend'=>true,
            'count_of_dates'=>2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'ひかり',
            'age' => 22,
            'occupation' => 'CA',
            'image_url'=> 'hogehoge',
            'user_id' => 1,
            'feature_first'=>'英語堪能',
            'feature_second' =>'帰国子女',
            'feature_third' =>'洋楽好き',
            'birthday'=>'',
            'address'=>'東京都大田区',
            'hobby'=>'旅行',
            'character'=>'社交的',
            'favorite_type_of_man'=>'趣味が合う人',
            'favorite_foods'=>'ハンバーグ',
            'dislike_foods'=>'甲殻類',
            'opportunity_to_meet'=>'合コンで知り合った',
            'notice'=>'まさにCAらしい雰囲気。',
            'has_boyfriend'=>true,
            'count_of_dates'=>2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'まい',
            'age' => 23,
            'occupation' => '医療機器メーカー',
            'image_url'=> 'hogehoge',
            'user_id' => 1,
            'feature_first'=>'モンクレ',
            'feature_second' =>'ジム通い',
            'feature_third' =>'',
            'birthday'=>'',
            'address'=>'東京都渋谷区',
            'hobby'=>'散歩',
            'character'=>'',
            'favorite_type_of_man'=>'',
            'favorite_foods'=>'',
            'dislike_foods'=>'',
            'opportunity_to_meet'=>'',
            'notice'=>'',
            'has_boyfriend'=>true,
            'count_of_dates'=>2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'あやな',
            'age' => 26,
            'occupation' => '証券会社',
            'image_url'=> 'hogehoge',
            'user_id' => 2,
            'feature_first'=>'',
            'feature_second' =>'',
            'feature_third' =>'',
            'birthday'=>'',
            'address'=>'',
            'hobby'=>'',
            'character'=>'',
            'favorite_type_of_man'=>'',
            'favorite_foods'=>'',
            'dislike_foods'=>'',
            'opportunity_to_meet'=>'',
            'notice'=>'',
            'has_boyfriend'=>true,
            'count_of_dates'=>2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'ゆか',
            'age' => 23,
            'occupation' => '広告代理店',
            'image_url'=> 'hogehoge',
            'user_id' => 3,
            'feature_first'=>'',
            'feature_second' =>'',
            'feature_third' =>'',
            'birthday'=>'',
            'address'=>'',
            'hobby'=>'',
            'character'=>'',
            'favorite_type_of_man'=>'',
            'favorite_foods'=>'',
            'dislike_foods'=>'',
            'opportunity_to_meet'=>'',
            'notice'=>'',
            'has_boyfriend'=>true,
            'count_of_dates'=>2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'ももこ',
            'age' => 22,
            'occupation' => '人材',
            'image_url'=> 'hogehoge',
            'user_id' => 4,
            'feature_first'=>'',
            'feature_second' =>'',
            'feature_third' =>'',
            'birthday'=>'',
            'address'=>'',
            'hobby'=>'',
            'character'=>'',
            'favorite_type_of_man'=>'',
            'favorite_foods'=>'',
            'dislike_foods'=>'',
            'opportunity_to_meet'=>'',
            'notice'=>'',
            'has_boyfriend'=>true,
            'count_of_dates'=>2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'みなみ',
            'age' => 23,
            'occupation' => '女医',
            'image_url'=> 'hogehoge',
            'user_id' => 5,
            'feature_first'=>'',
            'feature_second' =>'',
            'feature_third' =>'',
            'birthday'=>'',
            'address'=>'',
            'hobby'=>'',
            'character'=>'',
            'favorite_type_of_man'=>'',
            'favorite_foods'=>'',
            'dislike_foods'=>'',
            'opportunity_to_meet'=>'',
            'notice'=>'',
            'has_boyfriend'=>true,
            'count_of_dates'=>2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'あやめ',
            'age' => 22,
            'occupation' => 'ネイリスト',
            'image_url'=> 'hogehoge',
            'user_id' => 6,
            'feature_first'=>'',
            'feature_second' =>'',
            'feature_third' =>'',
            'birthday'=>'',
            'address'=>'',
            'hobby'=>'',
            'character'=>'',
            'favorite_type_of_man'=>'',
            'favorite_foods'=>'',
            'dislike_foods'=>'',
            'opportunity_to_meet'=>'',
            'notice'=>'',
            'has_boyfriend'=>true,
            'count_of_dates'=>2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'みゆ',
            'age' => 23,
            'occupation' => '保険外交員',
            'image_url'=> 'hogehoge',
            'user_id' => 7,
            'feature_first'=>'',
            'feature_second' =>'',
            'feature_third' =>'',
            'birthday'=>'',
            'address'=>'',
            'hobby'=>'',
            'character'=>'',
            'favorite_type_of_man'=>'',
            'favorite_foods'=>'',
            'dislike_foods'=>'',
            'opportunity_to_meet'=>'',
            'notice'=>'',
            'has_boyfriend'=>true,
            'count_of_dates'=>2,
            'created_at' => now(),
            'updated_at' => now(),
            ],
        ]);
    }
}
