<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
        [
        'name' => 'test',
        'email' => 'example@example.example',
        'email_verified_at' => now(),
        'password'=>Hash::make('exampleexample'),
        'image_url'=>'hoge',
        'occupation' => 'Web開発者',
        'birthday' => '1994-08-03',
        'address' => '東京都港区麻布十番',
        'hobby' => 'サウナ',
        'girl_experiences' => '5',
        'favorite_date_place' => '広尾周辺',
        'favorite_date_time' => '昼間',
        'favorite_clothes' => '恵比寿女子',
        'favorite_character' => 'ちゃんと話ができる',
        'favorite_feature' => 'たぬき顔巨乳',
        'favorite_age_range' => '20代後半〜30代前半',
        'notice' => '頑張って身体を鍛えます。',
        'created_at'=>now(),
        'updated_at'=>now(),
        ],
        [
            'name' => 'まさき',
            'email' => 'example@masaki.example',
            'email_verified_at' => now(),
            'password'=>Hash::make('Kisiemon@0803'),
            'image_url'=>'hoge',
            'occupation' => 'Webデザイナー',
            'birthday' => '1990-05-15',
            'address' => '東京都新宿区',
            'hobby' => '写真撮影',
            'girl_experiences' => '3',
            'favorite_date_place' => '代々木公園',
            'favorite_date_time' => '夕方',
            'favorite_clothes' => 'カジュアル',
            'favorite_character' => '優しい',
            'favorite_feature' => '笑顔',
            'favorite_age_range' => '20代後半〜40代前半',
            'notice' => 'お互いに楽しめるデートをしましょう。',
            'created_at'=>now(),
            'updated_at'=>now(),
        ],
        [
            'name' => 'しんや',
            'email' => 'example@shinya.example',
            'email_verified_at' => now(),
            'password'=>Hash::make('Kisiemon@0803'),
            'image_url'=>'hoge',
            'occupation' => 'エンジニア',
            'birthday' => '1992-11-30',
            'address' => '東京都渋谷区',
            'hobby' => '読書',
            'girl_experiences' => '2',
            'favorite_date_place' => '渋谷スクランブル交差点',
            'favorite_date_time' => '夜',
            'favorite_clothes' => 'カジュアル',
            'favorite_character' => '知的',
            'favorite_feature' => '眼鏡',
            'favorite_age_range' => '20代後半〜30代前半',
            'notice' => 'よろしくお願いします。',
            'created_at'=>now(),
            'updated_at'=>now(),
        ],
        [
        'name' => 'おたけ',
            'email' => 'example@otake.example',
            'email_verified_at' => now(),
            'password'=>Hash::make('Kisiemon@0803'),
            'image_url'=>'hoge',
            'occupation' => '教師',
            'birthday' => '1988-09-20',
            'address' => '東京都品川区',
            'hobby' => '料理',
            'girl_experiences' => '4',
            'favorite_date_place' => '浜離宮恩賜公園',
            'favorite_date_time' => '昼間',
            'favorite_clothes' => 'おしゃれ',
            'favorite_character' => '思いやりがある',
            'favorite_feature' => '料理上手',
            'favorite_age_range' => '30代前半〜40代前半',
            'notice' => '一緒に楽しい時間を過ごしましょう。',
            'created_at'=>now(),
            'updated_at'=>now(),
        ],
        [
            'name' => 'たかのり',
            'email' => 'example@takanori.example',
            'email_verified_at' => now(),
            'password'=>Hash::make('Kisiemon@0803'),
            'image_url'=>'hoge',
            'occupation' => 'エンジニア',
            'birthday' => '1992-11-30',
            'address' => '東京都渋谷区',
            'hobby' => '読書',
            'girl_experiences' => '2',
            'favorite_date_place' => '渋谷スクランブル交差点',
            'favorite_date_time' => '夜',
            'favorite_clothes' => 'カジュアル',
            'favorite_character' => '知的',
            'favorite_feature' => '眼鏡',
            'favorite_age_range' => '20代後半〜30代前半',
            'notice' => 'よろしくお願いします。',
            'created_at'=>now(),
            'updated_at'=>now(),
        ],
        [
            'name' => 'しゅうえい',
            'email' => 'example@shuei.example',
            'email_verified_at' => now(),
            'password'=>Hash::make('Kisiemon@0803'),
            'image_url'=>'hoge',
            'occupation' => 'エンジニア',
            'birthday' => '1992-11-30',
            'address' => '東京都渋谷区',
            'hobby' => '読書',
            'girl_experiences' => '2',
            'favorite_date_place' => '渋谷スクランブル交差点',
            'favorite_date_time' => '夜',
            'favorite_clothes' => 'カジュアル',
            'favorite_character' => '知的',
            'favorite_feature' => '眼鏡',
            'favorite_age_range' => '20代後半〜30代前半',
            'notice' => 'よろしくお願いします。',
            'created_at'=>now(),
            'updated_at'=>now(),
        ],
            [
            'name' => 'だいち',
            'email' => 'example@daichi.example',
            'email_verified_at' => now(),
            'password'=>Hash::make('Kisiemon@0803'),
            'image_url'=>'hoge',
            'occupation' => 'エンジニア',
            'birthday' => '1992-11-30',
            'address' => '東京都渋谷区',
            'hobby' => '読書',
            'girl_experiences' => '2',
            'favorite_date_place' => '渋谷スクランブル交差点',
            'favorite_date_time' => '夜',
            'favorite_clothes' => 'カジュアル',
            'favorite_character' => '知的',
            'favorite_feature' => '眼鏡',
            'favorite_age_range' => '20代後半〜30代前半',
            'notice' => 'よろしくお願いします。',
            'created_at'=>now(),
            'updated_at'=>now(),
        ],
            [
            'name' => 'かつのり',
            'email' => 'example@katsu.example',
            'email_verified_at' => now(),
            'password'=>Hash::make('Kisiemon@0803'),
            'image_url'=>'hoge',
            'occupation' => 'エンジニア',
            'birthday' => '1992-11-30',
            'address' => '東京都渋谷区',
            'hobby' => '読書',
            'girl_experiences' => '2',
            'favorite_date_place' => '渋谷スクランブル交差点',
            'favorite_date_time' => '夜',
            'favorite_clothes' => 'カジュアル',
            'favorite_character' => '知的',
            'favorite_feature' => '眼鏡',
            'favorite_age_range' => '20代後半〜30代前半',
            'notice' => 'よろしくお願いします。',
            'created_at'=>now(),
            'updated_at'=>now(),
        ]
        ]);
    }
}
